### ISSUE TITLE
Having to save files twice to get them working in browser

### ISSUE THREAD

**Issue by budda** [rblopes/generator-phaser-plus#10]
When I edit a file in Atom editor I need to save it twice before the new code is available in my browser, Chrome.

I can see the gulp stuff working in the terminal on each save -- but the new files are not being re-loaded in the browser it seems.

Is there a way to force the web browser to be using the new build output without me sacing each edited file twice?

**Comment by rblopes** [comment]
Unfortunately, only solution I know at the moment is to restart the project server. I'm not sure about what causes this issue, maybe BrowserSync is not triggering the page reload properly. I see this issue when switching branches inside a game project, but that happens very occasionally.

**Comment by rblopes** [comment]
A new version of the generator was published with a correction for this issue.
