### ISSUE TITLE
Defining a tilemap causes Phaser.Tilemap is not a constructor error

### ISSUE THREAD

**Issue by budda** [rblopes/generator-phaser-plus#17]
If i try:
```
  create() {
    //  Creates a blank tilemap
    var map = this.add.tilemap('map');
```

I get the error ```Uncaught TypeError: Phaser.Tilemap is not a constructor``` -- whats the correct way to create a timemap using the generators structure?

**Comment by rblopes** [comment]
Are you using the "no physics" build option? If so, there's no Tilemap class. You should at least choose the "Arcade Physics" build to get Tilemaps working. This is how Phaser was designed.

Check the tasks configuration (`gulpfile.js/config.js`) to change the Phaser build option.

**Comment by budda** [comment]
Yup no physics! That would explain it. *facepalm*
