### ISSUE TITLE
Installing plugin: kinnetic-scrolling

### ISSUE THREAD

**Issue by syzer** [rblopes/generator-phaser-plus#23]
I have a problem installing 
[](http://jdnichollsc.github.io/Phaser-Kinetic-Scrolling-Plugin/)

I was trying to follow.. 
[](https://github.com/rblopes/generator-phaser-plus/issues/16)
to no avail.

**Comment by rblopes** [comment]
Install the plugin using npm and then `require` (or `import`) it into your game app. From there, just follow the instructions at the plugin's page.

Bear in mind that this plugin isn't a CommonJS module (like _many_ others), it'll just appear as an `Phaser.Plugin` 'class' after you require it.

------

Hint: I edited a little [user's manual](/rblopes/generator-phaser-plus/blob/master/docs/index.md) covering this and a few other aspects of the generator and Phaser game authoring. It's not that great but I think you'll find it useful.

**Comment by syzer** [comment]
thanks so much!
