### ISSUE TITLE
Generator hangs on README exists

### ISSUE THREAD

**Issue by joehannes** [rblopes/generator-phaser-plus#24]
If a README exists I'm prompted what to do but the generator hangs instead of accepting input

**Comment by rblopes** [comment]
Can you confirm that only happens when there is a `README.md` file in the working folder? Does that happen when any other file that may get overwritten by the generator?

Also I need to know your OS, and which versions of Node.js and npm (or Yarn) you're using.

**Comment by joehannes** [comment]
I can confirm it started working when I had the idea the existing README is the ... and removed it.
I actually tried it again now and plaid with it, it also hangs on other files if they exist (tested: package.json)

how to reproduce ... simply run the generator twice in the same dir, you may ctrl+c the npm install

OS: Ubuntu 17.04
Node: 8.1.0
npm: 5.0.3

Cheers

**Comment by rblopes** [comment]
I'll request you to upgrade to Node.js v8.1.2 then. Your issue seems related to a regression in the `readline` module found recently (sources: [1], [2]).

[1]: https://github.com/nodejs/node/issues/13557
[2]: https://github.com/SBoudrias/Inquirer.js/issues/555

**Comment by joehannes** [comment]
I can confirm that as well.
I updated to 8.1.2 and it started working :)
Thx
