### ISSUE TITLE
Migrate to Yeoman?

### ISSUE THREAD

**Issue by rblopes** [rblopes/generator-phaser-plus#5]
Been considering migrating this generator to Yeoman for quite a while. Some limitations of using Gulp as a scaffolding tool are showing up and these may become more difficult to address over time.

My main concerns are:

1. Testing: current test suites are brittle, but not on purpose. Some cases, like inspecting the contents of some generated files, are not covered yet. Writing some of these tests require reading the Gulp streaming internals directly. I can write the necessary fixtures for that (I'll have to research how to accomplish this, though), but I'm pondering if this is worth all the trouble.

1. `gulp-install`: incompatible changes made to this task plugin since `0.3.0` are incompatible with the current project setup. Version `0.4.0` conflicted Bower and tests. Now, Bower is gone from the template project, so upgrading to `0.4.0` is not a problem, but tests run much slower with that version. `0.5.0` completely breaks the test suites, and I couldn't get it work at all. Again, I may replace this plugin with a more suitable one, perhaps `gulp-spawn` but, again, I'm considering if I should be doing this.

Suffice to say that much of these issues are addressed in Yeoman already. Only thing that holds me back is there are many Yeoman generators related to Phaser published already.

Should I decide to move forward and begin developing a new project based on this one's project template, further development and support for `slush-phaser-plus` will cease and its npm package will be deprecated in favor of the new solution instead.

I may be adding more details to this issue later.

**Comment by budda** [comment]
So many options for Yeoman, yet none seem to be keeping maintained. I think yours is the most recent and active scaffolding project for Phaser which caught my attention - but just seen this issue so wondering if to wait.

I have no prior experience with Yeoman to input on your questions sadly.

**Comment by rblopes** [comment]
I'm closing this issue now. As of today (2015-11-29), this project is fully ported to the Yeoman infrastructure. `v0.1.0` of `generator-phaser-plus` is its first release, now on npm. Time to focus on the documentation of the sample project now.
